### ISSUE TITLE
Add comparative data

### ISSUE THREAD

**Issue by jbranigan** [azavea/adb-mongolia-nua#24]
In popup and on report page, add some comparisons for the soum relative to its cluster (if it's in one), and relative to the whole country. This will only be for select indicators - tbd.

**Comment by rmartz** [comment]
- Fall back to compare with country if soum doesn't belong in any clusters

**Comment by CloudNiner** [comment]
Reuse this: https://github.com/azavea/mos-energy-benchmark/blob/develop/app/scripts/charting/histogram-directive.js

**Comment by designmatty** [comment]
I'm going to assign this to myself so I remember to finalize the design.
