### ISSUE TITLE
Style urban clusters and settlements

### ISSUE THREAD

**Issue by dmcglone** [azavea/adb-mongolia-nua#28]
Style urban cluster polygons and settlement points

**Comment by dmcglone** [comment]
![pop in poverty with urban clusters case and fill 2](https://cloud.githubusercontent.com/assets/1688859/18065602/7df9d410-6e02-11e6-9db5-dd54fe7b6849.png)
![pop in poverty with urban clusters no case fill solid line 3](https://cloud.githubusercontent.com/assets/1688859/18065601/7defb71e-6e02-11e6-998a-61dcfec08758.png)
![pop in poverty with urban clusters 1](https://cloud.githubusercontent.com/assets/1688859/18065600/7deda4d8-6e02-11e6-9b04-b131b532d2d9.png)

@jbranigan and @eneedham, here are a few examples of what this could look like with clusters overlaid along with a very light opaque polygon fill. the cartocss is tricky with dashed line arrays, any thicker or longer dashes and it's really messy in with curved edges.

**Comment by jbranigan** [comment]
I wonder if you set the line width to ~8px with an opacity of 50% if that boundary would work above the aimag boundaries...

**Comment by dmcglone** [comment]
Cluster boundaries below
![adb-mongolia-urbanclusters1](https://cloud.githubusercontent.com/assets/1688859/18073162/cb34d688-6e31-11e6-8f52-1b550962aadd.png)

Cluster boundaries above
![adb-mongolia-urbanclusters2](https://cloud.githubusercontent.com/assets/1688859/18073179/e23bca12-6e31-11e6-8280-802692bcaf44.png)

**Comment by jbranigan** [comment]
Tried with hatching the clusters with heavy boundaries. Aimags are just 1px black borders, and I removed the thin white Soum borders to quiet noise. Can't tell if it's easier to distinguish or not. The labels seem to help.

![image](https://cloud.githubusercontent.com/assets/1508618/18091790/dc34c2f2-6e97-11e6-978b-eaffa9aa98db.png)

**Comment by dmcglone** [comment]
Added these to all existing maps and also styled in separate maps @rmartz created.
