### ISSUE TITLE
Mongolian translations

### ISSUE THREAD

**Issue by dmcglone** [azavea/adb-mongolia-nua#41]
Translations into Mongolian for website completed by ADB team. 

Located here: \FILESHARE\projects\ADB_Mongolia_NUA\documents\translations\2016_10_06_ADB_Azavea_Translations BG Complete.xlsx

**Comment by rmartz** [comment]
These should be good to go in #43. Some newer messages were added after this batch, so we'll need to get them translated as well:

| String key | English text |
| --- | --- |
| CLUSTER_LEGEND_LABEL | Cluster average |
| COUNTRY_LEGEND_LABEL | Country average |
| HISTOGRAM_ECONOMY_TITLE | Distribution of total # of enterprises by soum |
| HISTOGRAM_HOUSEHOLDS_TITLE | Distribution of # of households by soum |
| HISTOGRAM_INFRASTRUCTURE_TITLE | Distribution of % of population with access to piped water by soum |
| HISTOGRAM_PEOPLE_TITLE | Distribution of population density by soum |
| MAP_ARCGIS_WORLD_IMAGERY_ATTRIBUTION | Source: Esri, DigitalGlobe, GeoEye, Earthstar Geographics, CNES/Airbus DS, USDA, USGS, AEX, Getmapping, Aerogrid, IGN, IGP, swisstopo, and the GIS User Community |
| MAP_ARCGIS_WORLD_TOPO_MAP_ATTRIBUTION | Sources: Esri, HERE, DeLorme, Intermap, increment P Corp., GEBCO, USGS, FAO, NPS, NRCAN, GeoBase, IGN, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong), swisstopo, MapmyIndia, Â© OpenStreetMap contributors, and the GIS User Community |
| MAP_DEFAULT_TITLE | Default |
| MAP_ARCGIS_WORLD_TOPO_MAP_TITLE | Topographical |
| MAP_ARCGIS_WORLD_IMAGERY_TITLE | Satellite |
| MAP_CLUSTERS_TITLE | Show regional clusters |
| MAP_ROADWAYS_TITLE | Show roadways |
| MAP_SETTLEMENTS_TITLE | Show major settlements |
| ZOOM_TO_AIMAG_PROMPT | Zoom to Aimag |
| ZOOM_TO_AIMAG_DEFAULT | Zoom to... |

I'm not sure about the two attribution strings, they're for a legal requirement so maybe we don't want them translated?

**Comment by jbranigan** [comment]
Google maps translates the attribution, so we might as well leave it in. Although, we might just need to translate "Source(s)". The couple of words at the end are "Terms" and "Leave Feedback", which we won't have.

![image](https://cloud.githubusercontent.com/assets/1508618/19284001/22851f90-8fc2-11e6-8a28-87870dd3fce1.png)

**Comment by dmcglone** [comment]
Before I follow up about this with ADB I want to check and see if we need any additional translations for the Khoroo data page @rmartz?

**Comment by rmartz** [comment]
@dmcglone Yeah there are a few additional phrases, this should be the list of what we have to be translated currently:

| String key | English text |
| --- | --- |
| DATA_KHOROO_HIERARCHY | Mongolia, Ulaanbaatar, {{khoroo_name}} |
| DATA_NO_DATA | No data available |
| MAP_VIS_UB_POP | Population 2015 |
| MAP_VIS_UB_POP_CHANGE | Population 2011-2015 |
| MAP_VIS_UB_POP_DENSITY | Density 2015 |
| MAP_VIS_UB_POP_PCT_ZERO_FIVE | Pop 0-5 |
| MAP_VIS_UB_POP_PCT_SIX_EIGHTEEN | Pop 6-18 |
| MAP_VIS_UB_POP_PCT_SIXTY_PLUS | Pop 60+ |
| MAP_VIS_UB_CHANGE_KINDERGARTEN | Change in Kindergarten |
| MAP_VIS_UB_CHANGE_PRIMARY | Change in Primary |
| MAP_VIS_UB_HSHD_COUNT | Number of Households |
| MAP_VIS_UB_POOR_HSHD_COUNT_CHANGE | Change in Poor Households |
| MAP_VIS_UB_CHANGE_WORK_AGE | Change in Working Age |
| MAP_VIS_UB_PCT_WORKING_AGE | Pop Working Age |
| MAP_VIS_UB_CHANGE_EMPLOYMENT | Change in Employment |
| MAP_VIS_UB_CHANGE_UNEMPLOYMENT | Change in Unemployment |
| CLUSTER_LEGEND_LABEL | Cluster average |
| COUNTRY_LEGEND_LABEL | Country average |
| ULAANBAATAR_LEGEND_LABEL | Ulaanbaatar average |
| HISTOGRAM_ECONOMY_TITLE | Distribution of total # of enterprises by soum |
| HISTOGRAM_HOUSEHOLDS_TITLE | Distribution of # of households by soum |
| HISTOGRAM_INFRASTRUCTURE_TITLE | Distribution of % of population with access to piped water by soum |
| HISTOGRAM_PEOPLE_TITLE | Distribution of population density by soum |
| HISTOGRAM_UB_PEOPLE_TITLE | Distribution of population density by khoroo |
| HISTOGRAM_UB_HOUSEHOLDS_TITLE | Distribution of households by khoroo |
| HISTOGRAM_UB_EMPLOYMENT_TITLE | Distribution of percent working age by khoroo |
| MAP_ARCGIS_WORLD_IMAGERY_ATTRIBUTION | Source: Esri, DigitalGlobe, GeoEye, Earthstar Geographics, CNES/Airbus DS, USDA, USGS, AEX, Getmapping, Aerogrid, IGN, IGP, swisstopo, and the GIS User Community |
| MAP_ARCGIS_WORLD_TOPO_MAP_ATTRIBUTION | Sources: Esri, HERE, DeLorme, Intermap, increment P Corp., GEBCO, USGS, FAO, NPS, NRCAN, GeoBase, IGN, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong), swisstopo, MapmyIndia, © OpenStreetMap contributors, and the GIS User Community |
| MAP_DEFAULT_TITLE | Default |
| MAP_ARCGIS_WORLD_TOPO_MAP_TITLE | Topographical |
| MAP_ARCGIS_WORLD_IMAGERY_TITLE | Satelite |
| MAP_CLUSTERS_TITLE | Show regional clusters |
| MAP_ROADWAYS_TITLE | Show roadways |
| MAP_SETTLEMENTS_TITLE | Show major settelemnts |
| ZOOM_TO_AIMAG_DEFAULT | Zoom to... |
| ZOOM_TO_AIMAG_PROMPT | Zoom to Aimag |

**Comment by jbranigan** [comment]
Note for the attributions that all we need are translations for "sources"

**Comment by dmcglone** [comment]
Final translations can be found in this document:

[2016_10_25_ADB_Azavea_FinalTranslations BG 102716.xlsx](https://github.com/azavea/adb-mongolia-nua/files/556043/2016_10_25_ADB_Azavea_FinalTranslations.BG.102716.xlsx)

**Comment by CloudNiner** [comment]
Just added the above strings to our translations file.  Looks like we're still missing a few translations:

| String key | English text |
| --- | --- |
| DATA_KHOROO_HIERARCHY | Mongolia, Ulaanbaatar, {{khoroo_name}} |
| DATA_NO_DATA | No data available |
| MAP_VIS_UB_POP_PCT_CHANGE_SIXTY_PLUS | % Change in 60+ |
| MAP_VIS_UB_POOR_HSHD_PCT | % Poor Households |

**Comment by dmcglone** [comment]
First two are in the spreadsheet but the last two are new. I'm going to infer those.

| String key | English text | Mongolian text |
| --- | --- | --- |
| DATA_KHOROO_HIERARCHY | Mongolia, Ulaanbaatar, {{khoroo_name}} | Монгол улс, Улаанбаатар хот, {{хороо}} |
| DATA_NO_DATA | No data available | Мэдээлэл байхгүй |
| MAP_VIS_UB_POP_PCT_CHANGE_SIXTY_PLUS | % Change in 60+ | 60+ насны хүн амын тоо өөрчлөлт |
| MAP_VIS_UB_POOR_HSHD_PCT | % Poor Households | Ядуу өрхийн тоон |

**Comment by CloudNiner** [comment]
Ah, thanks for double-checking. Sure, inferred sounds good.

**Comment by CloudNiner** [comment]
All strings translated, closing.
