### ISSUE TITLE
Add comments to app configuration file

### ISSUE THREAD

**Issue by jcahail** [azavea/adb-mongolia-nua#54]
To allow someone in Mongolia (presumably with limited experience) can update the app with new data

**Comment by CloudNiner** [comment]
After reviewing the JS config file, the comments there alone will not allow someone with "limited experience" to update the app with new data. Most of the configuration just defines which visualizations display in which categories on the National and Ulaanbaatar data pages, along with a few colors for the charts on the detail pages.

Any more clarification on what someone with "limited experience" means? Is it limited software development experience (e.g. HTML/CSS)? Limited Carto experience? Limited computer experience? 

Does "update with new data" refer to the data in the current data columns? Does it include adding new columns+visualizations?

I think in any case we'll need more of a word document how-to, with screenshots and step-by-step instructions, that can't be provided by just comments in the config. If the 'limited experience' refers to more of 'limited computer experience', that document will need to be more detailed. Either way, I think more time is warranted to address this issue.

**Comment by jcahail** [comment]
From Daniel: It's hard to say - but I would estimate limited software and next to no CARTO experience, but they will be proficient using computers
